### ISSUE TITLE
Consider adding bitcoin donation address to readme?

### ISSUE THREAD

**Issue by mr-highball** [r1me/TPocketSphinx#1]
Thank you for the work on this as it will save me a good deal of time. I would be more than happy to donate, but I prefer btc for donations.

**Comment by r1me** [comment]
Thanks for your interest in this project and suggestion on donation method. I will add a Bitcoin address in readme's of my open source projects. TPocketSphinx will actually receive an update. Based on Android wrapper of PocketSphinx there will be new recognizer modes where spoken words can be recognized partially and with a timeout value.

**Comment by mr-highball** [comment]
Sounds good, just comment back here when it's been added and I'll donate/close this issue.

**Comment by r1me** [comment]
Thanks, I've added it to [the readme](https://github.com/r1me/TPocketSphinx#donate).

**Comment by mr-highball** [comment]
Cool, btc sent, closing issue.
Keep up the good stuff 👍
